In [1]:
import numpy
numpy.__version__

'1.19.5'

In [2]:
import numpy as np

In [3]:
result = 0
for i in range(100):
    result += i

In [4]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
type(L[0])

int

In [6]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
type(L2[0])

str

In [8]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [9]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
import numpy as np

In [11]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [12]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [13]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [14]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [15]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [18]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [22]:
np.random.random((3, 3))

array([[0.07450153, 0.39082975, 0.54371219],
       [0.84996524, 0.76000465, 0.44536266],
       [0.92019932, 0.42368778, 0.58845263]])

In [23]:
np.random.normal(0, 1, (3, 3))

array([[-0.22220293,  0.13602519,  0.14527814],
       [ 1.44245057, -0.08023001,  0.31854261],
       [-0.40684947,  0.87389688,  0.06887593]])

In [24]:
np.random.normal(0, 9, (3, 3))

array([[  0.530696  ,  -0.98146124,  -5.04631087],
       [  5.01183526, -18.52141536,  14.91281936],
       [ -7.97786991,  -8.7823534 ,  -5.47394977]])

In [25]:
np.random.randint(0, 10, (3, 3))

array([[9, 2, 6],
       [4, 6, 8],
       [6, 7, 4]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.empty(3)

array([1., 1., 1.])

In [28]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [29]:
print("x3 ndim: ", x3.ndim)        #ndim (the number of dimensions)
print("x3 shape:", x3.shape)       #shape (the size of each dimension)
print("x3 size: ", x3.size)        #size (the total size of the array)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [30]:
print("dtype:", x3.dtype)

dtype: int32


In [31]:
print("itemsize:", x3.itemsize, "bytes")   # itemsize, which lists the size (in bytes) of each array element
print("nbytes:", x3.nbytes, "bytes")       # nbytes, which lists the total size (in bytes) of the array

itemsize: 4 bytes
nbytes: 240 bytes


In [32]:
x1

array([5, 0, 3, 3, 7, 9])

In [33]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [34]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [35]:
x1

array([5, 0, 3, 3, 7, 9])

In [36]:
x1[0]

5

In [37]:
x1[5]

9

In [38]:
x1[-1]

9

In [39]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [40]:
x2[0,0]

3

In [41]:
x2[0, -1]

4

In [42]:
x2[-1, 0]

1

In [43]:
x2[-1, -1]

7

In [44]:
x2[0,0] = 12

In [45]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [46]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

In [47]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [49]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [50]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [51]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [52]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [53]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [54]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [55]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [56]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [57]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [58]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [59]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [60]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In [61]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


In [62]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [63]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [64]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [65]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [66]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [67]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [68]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [69]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [70]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [71]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [72]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [73]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [74]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [75]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [76]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [77]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [78]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [79]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [80]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [81]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [82]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [84]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [85]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [86]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

2.77 s ± 291 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [87]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [88]:
%timeit (1.0 / big_array)

3.92 ms ± 914 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [89]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [90]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [91]:
x = np.arange(9).reshape((3, 3))
3 ** x

array([[   1,    3,    9],
       [  27,   81,  243],
       [ 729, 2187, 6561]], dtype=int32)

In [92]:
x = np.arange(9).reshape((3, 3))
1 ** x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [93]:
x = np.arange(9).reshape((3, 3))
0 ** x

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [94]:
x = np.arange(4)

print("x     =", x)

print("x + 5 =", x + 5)

print("x - 5 =", x - 5)

print("x * 2 =", x * 2)

print("x / 2 =", x / 2)

print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [95]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [96]:
-(0.5*x + 1) ** 2


array([-1.  , -2.25, -4.  , -6.25])

In [97]:
np.add(x, 2)

array([2, 3, 4, 5])

In [98]:
np.subtract(x, 2)

array([-2, -1,  0,  1])

In [99]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [100]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [101]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [102]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [103]:
x = np.array([5 - 6j, 7 - 8j, 2 + 4j, 0 + 1j])
np.abs(x)

array([ 7.81024968, 10.63014581,  4.47213595,  1.        ])

In [104]:
theta = np.linspace(0, np.pi, 3)

In [105]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [106]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [107]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))
print("2^x   =", np.power(2, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]
2^x   = [2 4 8]


In [108]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [109]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [110]:
from scipy import special

In [111]:
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [112]:
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


In [113]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [114]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [115]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [116]:
np.multiply.reduce(x)

120

In [117]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [118]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [119]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [120]:
L = np.random.random(100)
sum(L)

50.461758453195614

In [121]:
np.sum(L)

50.46175845319564

In [122]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

204 ms ± 28.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
745 µs ± 22.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [123]:
min(big_array), max(big_array)

(7.071203171893359e-07, 0.9999997207656334)

In [124]:
np.min(big_array), np.max(big_array)

(7.071203171893359e-07, 0.9999997207656334)

In [125]:
%timeit min(big_array)
%timeit np.min(big_array)

112 ms ± 28.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
381 µs ± 4.42 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [126]:
M = np.random.random((3, 4))
print(M)

[[0.79832448 0.44923861 0.95274259 0.03193135]
 [0.18441813 0.71417358 0.76371195 0.11957117]
 [0.37578601 0.11936151 0.37497044 0.22944653]]


In [127]:
M.sum()

5.1136763453287335

In [128]:
M.min(axis=0)

array([0.18441813, 0.11936151, 0.37497044, 0.03193135])

In [129]:
M.max(axis=0)

array([0.79832448, 0.71417358, 0.95274259, 0.22944653])

In [130]:
M.min(axis=1)

array([0.03193135, 0.11957117, 0.11936151])

In [131]:
M.max(axis=1)

array([0.95274259, 0.76371195, 0.37578601])

In [132]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [133]:
a = np.array([0, 1, 2])
a + 5

array([5, 6, 7])

In [134]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [135]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [136]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [137]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [138]:
M = np.ones((2, 3))
a = np.arange(3)

In [139]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [140]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [141]:
a = np.arange(3).reshape((3, 1))

In [142]:
a

array([[0],
       [1],
       [2]])

In [143]:
b = np.arange(3)

In [144]:
b

array([0, 1, 2])

In [145]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [146]:
M = np.ones((3, 2))
a = np.arange(3)

In [147]:
M

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [148]:
a

array([0, 1, 2])

In [149]:
M + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [150]:
a[:, np.newaxis].shape

(3, 1)

In [151]:
M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

In [152]:
np.logaddexp(M, a[:, np.newaxis])

array([[1.31326169, 1.31326169],
       [1.69314718, 1.69314718],
       [2.31326169, 2.31326169]])

In [153]:
X = np.random.random((10, 3))

In [154]:
x

array([1, 2, 3, 4, 5])

In [155]:
Xmean = X.mean(0)
Xmean

array([0.49831076, 0.50193438, 0.46752888])

In [156]:
X_centered = X - Xmean

In [157]:
X_centered

array([[-0.42378289, -0.08349676,  0.53186304],
       [ 0.1714334 ,  0.04523996,  0.35958216],
       [-0.26734032, -0.33910286, -0.18802404],
       [ 0.08709493,  0.40463975, -0.28081862],
       [-0.42568224, -0.49508048, -0.39219616],
       [ 0.27283678,  0.44309377,  0.32643444],
       [ 0.31419383,  0.18112764, -0.37610672],
       [ 0.23112091, -0.00215657,  0.41322288],
       [ 0.2735726 , -0.16584049, -0.11082735],
       [-0.23344699,  0.01157605, -0.28312962]])

In [158]:
X_centered.mean(0)

array([-4.44089210e-17,  3.33066907e-17, -9.43689571e-17])

In [159]:
x = np.linspace(0, 5, 50)
y = np.linspace(0, 5, 50)[:, np.newaxis]

z = np.sin(x) ** 10 + np.cos(10 + y * x) * np.cos(x)
z

array([[-0.83907153, -0.83470697, -0.8216586 , ...,  0.8956708 ,
         0.68617261,  0.41940746],
       [-0.83907153, -0.82902677, -0.8103873 , ...,  0.92522407,
         0.75321348,  0.52508175],
       [-0.83907153, -0.82325668, -0.79876457, ...,  0.96427357,
         0.84172689,  0.66446403],
       ...,
       [-0.83907153, -0.48233077, -0.01646558, ...,  0.96449925,
         0.75196531,  0.41982581],
       [-0.83907153, -0.47324558,  0.00392612, ...,  0.92542163,
         0.68540362,  0.37440839],
       [-0.83907153, -0.46410908,  0.02431613, ...,  0.89579384,
         0.65690314,  0.40107702]])

In [160]:
x = np.array([1, 2, 3, 4, 5])

In [161]:
x

array([1, 2, 3, 4, 5])

In [162]:
x < 3  # less than

array([ True,  True, False, False, False])

In [163]:
x > 3  # greater than

array([False, False, False,  True,  True])

In [164]:
x <= 3  # less than or equal

array([ True,  True,  True, False, False])

In [165]:
x >= 3  # greater than or equal

array([False, False,  True,  True,  True])

In [166]:
x != 3  # not equal

array([ True,  True, False,  True,  True])

In [167]:
x == 3  # equal

array([False, False,  True, False, False])

In [168]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [169]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [170]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [171]:
x > 6

array([[False, False, False, False],
       [ True,  True, False, False],
       [False, False,  True, False]])

In [172]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [173]:
np.count_nonzero(x < 6)

8

In [174]:
np.sum(x < 6)

8

In [175]:
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [176]:
np.any(x > 8)

True

In [177]:
np.any(x < 1)

True

In [178]:
np.any(x < 0)

False

In [179]:
np.all(x < 10)

True

In [180]:
np.all(x == 6)

False

In [181]:
np.all(x < 8, axis=1)

array([ True, False,  True])

In [182]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [183]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [184]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])

In [185]:
bool(1), bool(0)

(True, False)

In [186]:
bool(42), bool(0)

(True, False)

In [187]:
bool(42 or 0)

True

In [188]:
bool(42 and 0)

False

In [189]:
bin(42)

'0b101010'

In [190]:
bin(59)

'0b111011'

In [191]:
bin(42 & 59)

'0b101010'

In [192]:
bin(42 | 59)

'0b111011'

In [193]:
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A | B

array([ True,  True,  True, False,  True,  True])

In [194]:
A or B

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [195]:
x = np.arange(10)
(x > 4) & (x < 8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [196]:
(x > 4) and (x < 8)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [197]:
rand = np.random.RandomState(42)

x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [198]:
[x[3], x[7], x[2]]

[71, 86, 14]

In [199]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

In [200]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [201]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [202]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
row
col

array([2, 1, 3])

In [203]:
[row, col]

[array([0, 1, 2]), array([2, 1, 3])]

In [204]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [205]:
[row, col]

[array([0, 1, 2]), array([2, 1, 3])]

In [206]:
X[row, col]

array([ 2,  5, 11])

In [207]:
X[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [208]:
row[:, np.newaxis], col

(array([[0],
        [1],
        [2]]),
 array([2, 1, 3]))

In [209]:
row[:, np.newaxis] * col

array([[0, 0, 0],
       [2, 1, 3],
       [4, 2, 6]])

In [210]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [211]:
X[2, [2, 0, 1]]

array([10,  8,  9])

In [212]:
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [213]:
mask = np.array([1, 0, 1, 0], dtype=bool)
X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [214]:
mean = [0, 0]
cov = [[1, 2],
       [2, 5]]
X = rand.multivariate_normal(mean, cov, 100)
X.shape

(100, 2)

In [215]:
indices = np.random.choice(X.shape[0], 20, replace=False)
indices

array([22, 34, 30, 40, 27, 12, 65,  5, 54, 74, 78, 96, 70, 18, 72, 89, 29,
       45, 36, 88])

In [216]:
selection = X[indices]  # fancy indexing here
selection.shape

(20, 2)

In [217]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [218]:
x[i] -= 10
print(x)

[ 0 89 89  3 89  5  6  7 89  9]


In [219]:
x = np.zeros(10)
x[[0, 0]] = [6]
print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [220]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [221]:
x = np.zeros(10)
x[[0, 0]] = [4]
print(x)

[4. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [222]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
x

array([4., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

In [223]:
x = np.zeros(10)
np.add.at(x, i, 1)
print(x)

[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


In [224]:
import numpy as np

def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x

In [225]:
x = np.array([2, 1, 4, 3, 5])
selection_sort(x)

array([1, 2, 3, 4, 5])

In [226]:
def bogosort(x):
    while np.any(x[:-1] > x[1:]):
        np.random.shuffle(x)
    return x

In [227]:
x = np.array([2, 1, 4, 3, 5])
bogosort(x)

array([1, 2, 3, 4, 5])

In [228]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [229]:
x.sort()
print(x)

[1 2 3 4 5]


In [230]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [231]:
x.argsort()

array([1, 0, 3, 2, 4], dtype=int64)

In [232]:
x[i]

array([1, 2, 3, 4, 5])

In [233]:
rand = np.random.RandomState(1)
X = rand.randint(0, 10, (4, 6))
print(X)

[[5 8 9 5 0 0]
 [1 7 6 9 2 4]
 [5 2 4 2 4 7]
 [7 9 1 7 0 6]]


In [234]:
np.sort(X, axis=0)

array([[1, 2, 1, 2, 0, 0],
       [5, 7, 4, 5, 0, 4],
       [5, 8, 6, 7, 2, 6],
       [7, 9, 9, 9, 4, 7]])

In [235]:
np.sort(X, axis=1)

array([[0, 0, 5, 5, 8, 9],
       [1, 2, 4, 6, 7, 9],
       [2, 2, 4, 4, 5, 7],
       [0, 1, 6, 7, 7, 9]])

In [236]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [237]:
np.partition(X, 2, axis=1)

array([[0, 0, 5, 9, 5, 8],
       [1, 2, 4, 9, 7, 6],
       [2, 2, 4, 5, 4, 7],
       [0, 1, 6, 7, 7, 9]])

In [238]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [239]:
x = np.zeros(4, dtype=int)

In [240]:
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [241]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [242]:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [243]:
data['age']

array([25, 45, 37, 19])

In [244]:
data['weight']

array([55. , 85.5, 68. , 61.5])

In [245]:
data[0]

('Alice', 25, 55.)

In [246]:
data[-1]['name']

'Doug'

In [247]:
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

In [248]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [249]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [250]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [251]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [252]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [253]:
data['age']

array([25, 45, 37, 19])

In [254]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19])

In [255]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

200 ns ± 32.7 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
3.2 µs ± 895 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
4.61 µs ± 1.26 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
