In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
np.__version__

'1.19.5'

In [3]:
x = [[1,2,3,4.0], [1,3,4,5.0]],[[1,2,3,4.0], [1,3,4,5.0]]
print(x)

([[1, 2, 3, 4.0], [1, 3, 4, 5.0]], [[1, 2, 3, 4.0], [1, 3, 4, 5.0]])


In [4]:
y = np.array(x)

In [5]:
y

array([[[1., 2., 3., 4.],
        [1., 3., 4., 5.]],

       [[1., 2., 3., 4.],
        [1., 3., 4., 5.]]])

In [6]:
y[:, 1:3]  # start row: end row , start col : end col

array([[[1., 3., 4., 5.]],

       [[1., 3., 4., 5.]]])

In [7]:
# scale is o dimen tensor
# vector is 1 dimen tensor
# marix is a 2 dimn tensor
# n dimen is n dim tensor

In [8]:
y

array([[[1., 2., 3., 4.],
        [1., 3., 4., 5.]],

       [[1., 2., 3., 4.],
        [1., 3., 4., 5.]]])

In [9]:
y[:, :2, 1:3]  #multi dimes slicing

array([[[2., 3.],
        [3., 4.]],

       [[2., 3.],
        [3., 4.]]])

In [10]:
np.random.seed(0)
k = np.random.rand(2,3,3,4)
k

array([[[[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
         [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
         [0.96366276, 0.38344152, 0.79172504, 0.52889492]],

        [[0.56804456, 0.92559664, 0.07103606, 0.0871293 ],
         [0.0202184 , 0.83261985, 0.77815675, 0.87001215],
         [0.97861834, 0.79915856, 0.46147936, 0.78052918]],

        [[0.11827443, 0.63992102, 0.14335329, 0.94466892],
         [0.52184832, 0.41466194, 0.26455561, 0.77423369],
         [0.45615033, 0.56843395, 0.0187898 , 0.6176355 ]]],


       [[[0.61209572, 0.616934  , 0.94374808, 0.6818203 ],
         [0.3595079 , 0.43703195, 0.6976312 , 0.06022547],
         [0.66676672, 0.67063787, 0.21038256, 0.1289263 ]],

        [[0.31542835, 0.36371077, 0.57019677, 0.43860151],
         [0.98837384, 0.10204481, 0.20887676, 0.16130952],
         [0.65310833, 0.2532916 , 0.46631077, 0.24442559]],

        [[0.15896958, 0.11037514, 0.65632959, 0.13818295],
         [0.19658236, 0.36872517, 0.82099323

In [11]:
k.shape

(2, 3, 3, 4)

In [12]:
k[:,:,:3,:2]

array([[[[0.5488135 , 0.71518937],
         [0.4236548 , 0.64589411],
         [0.96366276, 0.38344152]],

        [[0.56804456, 0.92559664],
         [0.0202184 , 0.83261985],
         [0.97861834, 0.79915856]],

        [[0.11827443, 0.63992102],
         [0.52184832, 0.41466194],
         [0.45615033, 0.56843395]]],


       [[[0.61209572, 0.616934  ],
         [0.3595079 , 0.43703195],
         [0.66676672, 0.67063787]],

        [[0.31542835, 0.36371077],
         [0.98837384, 0.10204481],
         [0.65310833, 0.2532916 ]],

        [[0.15896958, 0.11037514],
         [0.19658236, 0.36872517],
         [0.83794491, 0.09609841]]]])

In [13]:
# random.randn is used to get values standard normal disturbution mean is 0 and std is 1 (values will get -3 to +3) i.e 99.7% lies in it

In [14]:
## random.rand is used to get values normal disturbution mran is 0 and std is 1 (values will get 0 to 1)

In [15]:
np.random.seed(0)
np.random.randint(4, 10, (3,4))

array([[8, 9, 4, 7],
       [7, 7, 5, 7],
       [9, 6, 8, 4]])

In [16]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.ones_like(k)    

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [19]:
np.zeros_like(k)    

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [20]:
np.ones_like(k)*2

array([[[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]],


       [[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]]])

In [21]:
np.ones_like(k)*4    

array([[[[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]],

        [[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]],

        [[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]]],


       [[[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]],

        [[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]],

        [[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]]]])

In [22]:
# BROAD CASTING

In [23]:
x = np.random.rand(4,5,2)
y = np.random.rand(4,2,5)
z = np.matmul(x,y)
z

array([[[0.34309477, 0.43058655, 0.61133016, 0.67309279, 1.04958158],
        [0.30370351, 0.39843278, 0.53675484, 0.69267748, 0.91648496],
        [0.27362969, 0.39993955, 0.47320472, 0.85366007, 0.79588624],
        [0.03129788, 0.04403586, 0.05455932, 0.08806139, 0.0922793 ],
        [0.09134199, 0.18126858, 0.14583797, 0.55265877, 0.23087895]],

       [[0.48308372, 0.36123047, 0.44449863, 0.80016324, 0.59520659],
        [0.56677036, 0.39629985, 0.45024043, 0.76411891, 0.71989549],
        [0.32304862, 0.26623564, 0.36116194, 0.69174502, 0.37867294],
        [0.14357881, 0.15470648, 0.25475702, 0.53842538, 0.13976415],
        [0.19738432, 0.22074446, 0.37111202, 0.79138942, 0.18581556]],

       [[0.68808656, 0.35669326, 0.52581342, 0.36183413, 0.55956207],
        [0.68997481, 0.59778614, 0.28866834, 0.34294298, 0.35146785],
        [0.72604358, 0.46405784, 0.46768798, 0.37453248, 0.5138737 ],
        [0.38931888, 0.4584011 , 0.04255125, 0.18347748, 0.09259081],
        [0.88605

In [24]:
x = np.random.rand(2,5,2)
y = np.random.rand(2,2,5)
z = np.matmul(x,y)
z

array([[[0.40489011, 1.30499167, 0.62599157, 1.30629196, 0.94303731],
        [0.26957939, 0.84665337, 0.40707231, 0.85769694, 0.61077993],
        [0.24246386, 0.7085158 , 0.34295802, 0.74271304, 0.50857144],
        [0.11904906, 0.4248121 , 0.20203724, 0.40636632, 0.30891773],
        [0.13682099, 0.5751631 , 0.27021758, 0.51414646, 0.42194161]],

       [[0.73392958, 0.57605736, 0.60403961, 0.41565797, 0.79395203],
        [0.7715373 , 0.58385361, 0.65532035, 0.34498827, 0.7294769 ],
        [1.26788656, 0.91697356, 1.11666722, 0.38703816, 0.99307881],
        [0.59037412, 0.4164766 , 0.52978718, 0.13576432, 0.41158335],
        [0.89054893, 0.6525596 , 0.77639062, 0.3077884 , 0.73861837]]])

In [25]:
x = np.random.rand(2,5,2)
y = np.random.rand(2,2,4)
z = np.matmul(x,y)
z

array([[[0.51865877, 0.83797241, 0.13457922, 0.81910205],
        [0.51108403, 0.88123554, 0.14545149, 0.90011468],
        [0.14522994, 0.3189284 , 0.05717968, 0.37055443],
        [0.50310513, 0.93302512, 0.15834214, 0.99586635],
        [0.51634733, 0.97574707, 0.16671125, 1.05250638]],

       [[0.82733896, 0.56677913, 0.57703366, 0.41887733],
        [0.98014729, 0.67693033, 0.63045891, 0.38046054],
        [0.97393503, 0.65257636, 0.82149517, 0.8028941 ],
        [1.14176784, 0.77804911, 0.83651542, 0.66559864],
        [0.7221887 , 0.47406381, 0.70472828, 0.80355588]]])

In [26]:
x = np.random.rand(2,5,2)
y = np.random.rand(2,5,2)
z = x+y
z

array([[[1.9097355 , 1.4697693 ],
        [0.54734689, 0.94988804],
        [1.46011259, 0.48357467],
        [0.91925767, 0.26418174],
        [0.38618953, 0.96289418]],

       [[1.5332485 , 0.7143835 ],
        [0.57276631, 1.18243778],
        [0.76244356, 0.46625556],
        [0.47649004, 1.31782189],
        [0.95498043, 0.4174965 ]]])

In [27]:
x = np.random.rand(2,5,2)
y = np.random.rand(2,5,2)
z = x**2 + 2 * y + x * y + 4 
z

array([[[4.37646219, 5.97418071],
        [6.30362566, 4.73463133],
        [6.69099779, 6.92106844],
        [5.74014281, 4.51993498],
        [5.81968173, 4.12742168]],

       [[4.41965108, 5.74658151],
        [4.97049175, 5.25195984],
        [5.06470816, 6.35185645],
        [6.66667886, 5.09914713],
        [5.25110839, 5.0064115 ]]])

In [28]:
x = np.random.rand(2,5,6)
y = np.random.rand(2,5,6)
z = x**2 + 2 * y + x * y + 4
z

array([[[5.62030492, 4.71331016, 4.65958786, 4.15023799, 5.57727032,
         4.26663109],
        [5.94165025, 5.31649885, 4.80562717, 4.80678582, 6.76814785,
         4.51816285],
        [5.37821418, 5.78211858, 7.47421942, 5.75184289, 4.66375705,
         4.2862114 ],
        [4.11192835, 5.74756679, 5.14862176, 5.88688632, 5.63843545,
         6.14304961],
        [4.58926049, 5.18019109, 5.49487286, 7.03651675, 4.24727132,
         6.98882339]],

       [[5.79150143, 7.19402898, 5.64925173, 5.68510348, 5.94311485,
         5.54854816],
        [4.93623388, 5.28210168, 5.58561761, 4.08999034, 5.99787882,
         4.187259  ],
        [6.51106685, 4.98922719, 5.68974894, 6.94132303, 5.66494236,
         4.09430768],
        [5.89052392, 5.15290157, 5.60795982, 5.56595109, 4.59192699,
         5.11219783],
        [6.1139655 , 7.75496245, 5.3657492 , 7.10684355, 5.37976391,
         4.95745643]]])

In [29]:
np.random.seed(0)
x = np.random.randint(2,10,(2,2))
y = np.random.randint(2,10,(2,2))
print(x)
print(y)

[[6 9]
 [7 2]]
[[5 5]
 [5 9]]


In [30]:
x * y

array([[30, 45],
       [35, 18]])

In [31]:
z = np.matmul(x,y)

In [32]:
z

array([[ 75, 111],
       [ 45,  53]])

In [33]:
np.random.seed(0)
x = np.random.randint(2,10,(2,3))
y = np.random.randint(2,10,(2,2))
print(x)
print(y)

[[6 9 7]
 [2 5 5]]
[[5 9]
 [3 5]]


In [35]:
k = np.zeros_like(x)
k

array([[0, 0, 0],
       [0, 0, 0]])

In [37]:
k[:, :2] = y 
k

array([[5, 9, 0],
       [3, 5, 0]])

In [42]:
print(x*k)

[[30 81  0]
 [ 6 25  0]]


In [44]:
print(x + k)

[[11 18  7]
 [ 5 10  5]]


In [49]:
x = np.array([1,2,3])
y = np.array([2])
print(x)
print(y)

[1 2 3]
[2]


In [50]:
print(x * y)

[2 4 6]
